FROM ghcr.io/huggingface/text-generation-inference:latest

RUN pip install inflect sqlparse
RUN pip3 install mlcroissant==1.0.8

COPY src /app/src
COPY data /app/data

WORKDIR /app
ENV HUGGINGFACE_HUB_CACHE=/transformers_cache